# Generated by Django 2.2.4 on 2022-02-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0003_auto_20220226_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='user_has_worker',
            field=models.ManyToManyField(related_name='workers', to='login_registration_app.User'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services_has_user', models.ManyToManyField(related_name='services', to='login_registration_app.User')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='login_registration_app.Worker')),
            ],
        ),
    ]
